version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/laojianzi/kql-go"

[[analyzers]]
name = "test-coverage"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"