
name: CI Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    name: Lint/Build/Test

    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version: ${{matrix.go-version}}

      - name: Diff
        run: go mod tidy && git diff --exit-code

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -covermode=atomic -coverprofile=cover.out ./...

      - uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          fail-ci-on-error: true
